#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
UPDATE_DIR="$HOME/.config/sketchybar/updates"

PADDINGS=3 # All paddings use this value (icon, label, background and bar paddings)
FONT="SF Pro Display"

bar=(
    sticky=on
    height=24
    blur_radius=25
    position=top
    padding_left=7
    padding_right=7
    color=$COLOR_BAR
    topmost=off
    shadow=on
    font_smoothing=off
)

sketchybar --bar "${bar[@]}"

defaults=(
    updates=when_shown                        
    label.font="$FONT:Semibold:13.0" 
    label.color=$COLOR_DEFAULT_LABEL          
    label.padding_left=$PADDINGS              
    label.padding_right=$PADDINGS             
    icon.font="$FONT:Semibold:15.0"  
    icon.color=$COLOR_DEFAULT_ICON            
    icon.padding_left=$PADDINGS               
    icon.padding_right=$PADDINGS              
    background.corner_radius=3                
    background.padding_left=$PADDINGS         
    background.padding_right=$PADDINGS
)

sketchybar --default "${defaults[@]}"

source "$ITEM_DIR/space.list.sh"
source "$ITEM_DIR/space.new.sh"
# source "$ITEM_DIR/space.zen.sh"
# source "$ITEM_DIR/space.mode.sh"

source "$ITEM_DIR/stando.sh"

source "$ITEM_DIR/calendar.clock.sh"
source "$ITEM_DIR/calendar.date.sh"

source "$ITEM_DIR/sound.output.sh"
source "$ITEM_DIR/sound.input.sh"

source "$ITEM_DIR/network.wifi.sh"
source "$ITEM_DIR/network.vpn.sh"

source "$ITEM_DIR/battery.sh"

source "$ITEM_DIR/message.indicator.sh"


source "$ITEM_DIR/upcoming.sh"

##### Finalizing Setup #####
sketchybar --update

echo "sketchybar configuration loaded.."
