#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float

# styling settings
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# focus border settings
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_blur           off
yabai -m config active_window_border_color   0xffe54073
yabai -m config normal_window_border_color   0x00ffffff
yabai -m config insert_feedback_color        0x00ffffff

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Settings$" layer=above manage=off
yabai -m rule --add app="^Finder$" layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="YabaiIndicator" sticky=on layer=above manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^Browserosaurus$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="^Installer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Step Two$" sticky=on layer=above manage=off
yabai -m rule --add app="^Scoot$" manage=off border=off
yabai -m rule --add app="^FortiClient$" layer=above manage=off border=off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   1

yabai -m config external_bar all:24:0

yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_title_changed &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger window_title_changed &> /dev/null"

yabai -m signal --add event=display_added action="sketchybar -m --trigger display_number_changed &> /dev/null"
yabai -m signal --add event=display_removed action="sketchybar -m --trigger display_number_changed &> /dev/null"
yabai -m signal --add event=mission_control_exit action="sketchybar -m --trigger space_number_changed &> /dev/null"

yabai -m signal --add event=space_changed action="sketchybar -m --trigger space_changed &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger space_changed &> /dev/null"

echo "yabai configuration loaded.."
