#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# general space settings
yabai -m config layout                       float

echo "yabai configuration loaded.."
